[package]
name = "finalproject"
version = "0.1.0"
edition = "2021"

[dependencies]
linfa = "0.6.0"
linfa-trees = "0.6.0"
ndarray = "0.15"
rand = "0.8"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
